### ISSUE TITLE
PCO not accessible after killed process

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/libuca#12]
If one quits a process with a PCO uca camera which is in recording state without calling `stop_recording` the camera is not accessible anymore. Even after the camera reset. The only thing which worked for me was to restart the PC with the frame grabber.

**Comment by matze** [comment]
I don't know if this is still valid after 4 1/2 years but in any case this is better reported at https://github.com/ufo-kit/uca-pco.

**Comment by tfarago** [comment]
Sounds about right :wink:
