### ISSUE TITLE
GUI frame skipping breaks acquisition on cam4

### ISSUE THREAD

**Issue by matze** [ufo-kit/libuca#66]
@TimoDritschler: commit 954bcbc39d6899bf causes the GUI to acquire only a single frame upon stopping the recording. However, so far this can only be observed on ipecam4 but regardless of the actual camera (even mock break).

**Comment by TimoDritschler** [comment]
I have tried and I can not reproduce the Problem on ipecamera4, neither with UFO cam nor with mock. Can you try again and demonstrate the problem to me?

**Comment by matze** [comment]
Just connect to ipecam4 and run the system-wide installation of `uca-camera-control` which is now again based on current HEAD with that commit.

**Comment by TimoDritschler** [comment]
I just freshly cloned the repo into my home directory on camera4, built it and installed it into my local usr dir. Everything works perfectly fine. So the same exact source code runs in one case but not the other. What does that tell us?

```bash
su root
$> cd software/libuca/build
$> rm -rf *
$> cmake .. -DCMAKE_INSTALL_PREFIX=/usr && make install
```
Works perfectly fine.

**Comment by matze** [comment]
> What does that tell us?

One more machine that is f'd up beyond recognition …
