### ISSUE TITLE
Data readout speed drop with small images

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/libuca#7]
I measured the readout speed with PCO software and it's the same as for big images (it took 9 minutes to download the full buffer of images with size cca 960x480). That is much faster than what we can do with libuca. I know there is the issue of being able to download only frame by frame on the PCO side, but maybe there is a new version of the library, or something else we could do about it. I mean their GUI is probably based on the same library, right? I can even try to contact the company if you haven't done so when you discovered it.

_Note:_ I know this is not a bug in libuca, that's why it's not tagged like it, but I would like to put some effort into this, because for fast experiments the DAQ time to data readout time ratio gets ridiculously small.

**Comment by matze** [comment]
Is this actually still a problem exclusive to libpco/libuca? Your latest measurements revealed the same problem with the vendor SDK on Windows. I'll close this for now but if required just re-open.
