### ISSUE TITLE
GI typelib require version gets messed up in Python

### ISSUE THREAD

**Issue by matze** [ufo-kit/libuca#82]
@tfarago if you have anything to add …

**Comment by matze** [comment]
@tfarago: I committed https://github.com/ufo-kit/concert/commit/3531ba5c40641e2c506f05e15390f6bbde02611f which fixes the warning for me *and* does not error out with strange messages. Maybe your system is screwed up with weird `GI_TYPELIB_PATH` overrides or some such?

**Comment by tfarago** [comment]
It doesn't work neither for the beam line user nor for me on the ankatoto-concert. I use virtual C environments though. Could you check it directly there please? I get:
```python
In [1]: import gi
In [2]: gi.require_version('Uca', '2.0')
In [3]: from gi.repository import GObject, GLib, Uca
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-f9773312ff06> in <module>()
----> 1 from gi.repository import GObject, GLib, Uca

/usr/lib/python2.7/dist-packages/gi/importer.pyc in load_module(self, fullname)
    138                 introspection_module = get_introspection_module(namespace)
    139             except RepositoryError as e:
--> 140                 raise ImportError(e)
    141             # Import all dependencies first so their init functions
    142             # (gdk_init, ..) in overrides get called.

ImportError: Typelib file /home/ws/jd2392/.local/share/cenv/ufo/lib/girepository-1.0/Uca-2.0.typelib for namespace 'Uca' contains version '2' which doesn't match the expected version '2.0'
```

**Comment by matze** [comment]
It's because that system is messed up (once again). I removed all the globally installed stuff in `/usr/local` (thanks for that) and at least in the `test` cenv it works from `~/dev/libuca-nonroot` (thanks for that) as expected:
```
master ⚒ test anka-bl-topo-to-0001@ankatoto-concert:~/dev/libuca python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Uca', '2.0')
>>> from gi.repository import Uca
>>>
```

It's still that working in the `ufo` cenv but I advise you to set up everything correctly from scratch and move the session's accordingly.
